version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: mediplus
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mediplus
      MYSQL_PASSWORD: mediplus
    ports:
      - "3306:3306"
