INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Annette', 'Hinton', 'CARDIOLOGIST', 'Dunn-Koch', 'annette.hinton@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Elizabeth', 'Palmer', 'CARDIOLOGIST', 'Smith-Johnson', 'elizabeth.palmer@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Barbara', 'Smith', 'CARDIOLOGIST', 'Nichols-Hunt', 'barbara.smith@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Melissa', 'Smith', 'CARDIOLOGIST', 'Malone PLC', 'melissa.smith@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Bonnie', 'Lewis', 'CARDIOLOGIST', 'Peterson, Allen and Garrett', 'bonnie.lewis@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Chad', 'Marshall', 'DERMATOLOGIST', 'Rosario Inc', 'chad.marshall@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Benjamin', 'Trujillo', 'DERMATOLOGIST', 'Norman-Brooks', 'benjamin.trujillo@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Michael', 'Hawkins', 'DERMATOLOGIST', 'Carter Group', 'michael.hawkins@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Patricia', 'Nicholson', 'DERMATOLOGIST', 'Miller Group', 'patricia.nicholson@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Wanda', 'Gonzales', 'DERMATOLOGIST', 'Castro-Cooper', 'wanda.gonzales@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Kathryn', 'Browning', 'DERMATOLOGIST', 'Riddle PLC', 'kathryn.browning@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Randy', 'Martinez', 'DERMATOLOGIST', 'Donovan, Rogers and Bell', 'randy.martinez@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Christopher', 'Frank', 'DERMATOLOGIST', 'Tucker-Davis', 'christopher.frank@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Karen', 'Jones', 'DERMATOLOGIST', 'Miller, Wagner and Lopez', 'karen.jones@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Luis', 'Daniels', 'ENDOCRINOLOGIST', 'Solomon-Haynes', 'luis.daniels@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Bradley', 'Hall', 'ENDOCRINOLOGIST', 'Soto-Day', 'bradley.hall@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Jorge', 'Carter', 'ENDOCRINOLOGIST', 'Kelly, Brown and Evans', 'jorge.carter@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Anita', 'Weaver', 'GASTROENTEROLOGIST', 'Henson-Chavez', 'anita.weaver@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Nicholas', 'Nelson', 'GASTROENTEROLOGIST', 'Shepherd, Price and White', 'nicholas.nelson@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Amber', 'Espinoza', 'GASTROENTEROLOGIST', 'Hawkins-Murillo', 'amber.espinoza@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Deborah', 'Myers', 'GASTROENTEROLOGIST', 'Keller-Avila', 'deborah.myers@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Jason', 'Mcknight', 'GYNECOLOGIST', 'Johnson Inc', 'jason.mcknight@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Susan', 'Fields', 'GYNECOLOGIST', 'Jones and Sons', 'susan.fields@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Kelly', 'Martin', 'GYNECOLOGIST', 'Ballard, Roberts and Blackwell', 'kelly.martin@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Nancy', 'Snyder', 'GYNECOLOGIST', 'Pitts, Moreno and Ho', 'nancy.snyder@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Randy', 'Butler', 'GYNECOLOGIST', 'Parker LLC', 'randy.butler@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Renee', 'Martin', 'HEMATOLOGIST', 'Campbell-Abbott', 'renee.martin@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Sharon', 'Randall', 'HEMATOLOGIST', 'Hester-Jones', 'sharon.randall@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Emily', 'Mckinney', 'HEMATOLOGIST', 'Vaughan Group', 'emily.mckinney@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Stephanie', 'Coleman', 'NEUROLOGIST', 'Holt-Lee', 'stephanie.coleman@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Jose', 'Henderson', 'NEUROLOGIST', 'Alvarado, Leach and Smith', 'jose.henderson@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Aaron', 'Young', 'NEUROLOGIST', 'Robertson-Smith', 'aaron.young@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Tina', 'Johnson', 'NEUROLOGIST', 'Macdonald Ltd', 'tina.johnson@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Christopher', 'Elliott', 'NEUROLOGIST', 'Wilson-Gamble', 'christopher.elliott@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Vanessa', 'Davis', 'OPHTHALMOLOGIST', 'Garcia, Brown and Page', 'vanessa.davis@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Edward', 'Anderson', 'OPHTHALMOLOGIST', 'Brown and Sons', 'edward.anderson@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Richard', 'Green', 'OPHTHALMOLOGIST', 'Hart PLC', 'richard.green@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Julie', 'Klein', 'OPHTHALMOLOGIST', 'Smith, Roberts and Salazar', 'julie.klein@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Brittany', 'Barrett', 'OPHTHALMOLOGIST', 'Ward-Carter', 'brittany.barrett@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Noah', 'Carr', 'OPHTHALMOLOGIST', 'Hobbs, Stone and Frye', 'noah.carr@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Shannon', 'Hunt', 'PEDIATRICIAN', 'Hardy LLC', 'shannon.hunt@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Barbara', 'Hall', 'PEDIATRICIAN', 'Thomas LLC', 'barbara.hall@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Nathan', 'Decker', 'PEDIATRICIAN', 'Rogers, Wong and Campbell', 'nathan.decker@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Stephanie', 'Woodard', 'PEDIATRICIAN', 'Mcintyre Inc', 'stephanie.woodard@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Kevin', 'Graham', 'PEDIATRICIAN', 'Fuentes-Avery', 'kevin.graham@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Kimberly', 'Little', 'PSYCHIATRIST', 'Barber-Mclaughlin', 'kimberly.little@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Kimberly', 'James', 'PSYCHIATRIST', 'Gonzalez, Morgan and Anderson', 'kimberly.james@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Cheryl', 'Nielsen', 'PSYCHIATRIST', 'Cooper-Bowen', 'cheryl.nielsen@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Brad', 'Morales', 'PSYCHIATRIST', 'Hunt Inc', 'brad.morales@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Kyle', 'Turner', 'PSYCHIATRIST', 'Schultz-Dudley', 'kyle.turner@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Philip', 'Potter', 'PSYCHIATRIST', 'Salazar, Jones and Duran', 'philip.potter@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Raymond', 'Gibson', 'PSYCHIATRIST', 'Serrano, Cross and Jimenez', 'raymond.gibson@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Leslie', 'Alvarez', 'PSYCHIATRIST', 'Wood Group', 'leslie.alvarez@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Philip', 'Jones', 'PSYCHIATRIST', 'Patterson-Stewart', 'philip.jones@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Gerald', 'Knight', 'UROLOGIST', 'Duran-Lane', 'gerald.knight@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Hayley', 'Watson', 'UROLOGIST', 'Lewis-Stafford', 'hayley.watson@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Cody', 'Cobb', 'UROLOGIST', 'Austin-Scott', 'cody.cobb@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Mark', 'Green', 'UROLOGIST', 'Robinson Group', 'mark.green@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Michael', 'Kidd', 'UROLOGIST', 'Hamilton, Williams and Rivera', 'michael.kidd@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Alexis', 'Martinez', 'UROLOGIST', 'Cochran and Sons', 'alexis.martinez@example.com');
INSERT INTO doctor (name, lastname, speciality, medical_center, email) VALUES ('Keith', 'Eaton', 'UROLOGIST', 'Williamson, Cook and Morgan', 'keith.eaton@example.com');
INSERT INTO patient (name, lastname, identification, age, phone) VALUES ('Tracy', 'Johnson', 77007, 15, '+1-650-300-5486');
INSERT INTO patient (name, lastname, identification, age, phone) VALUES ('Roger', 'Murphy', 77080, 98, '001-706-623-1035');
